import { ANDROID_API_KEY, IOS_API_KEY, ANDROID_OAUTH_CREDENTIALS,IOS_OAUTH_CREDENTIALS, GOOGLE_PLACES_API_KEY,SERVICE_KEY } from 'react-native-dotenv';

export default { 
  ANDROID_API_KEY,
  IOS_API_KEY,
  IOS_OAUTH_CREDENTIALS,
  ANDROID_OAUTH_CREDENTIALS,
  SERVICE_KEY,
  GOOGLE_PLACES_API_KEY
};